### ISSUE TITLE
Importing notes error in Chrome

### ISSUE THREAD

**Issue by mike-st** [fabiobeoni/adapt-notes#1]
Hi their love the extension and works great! Many thanks for all your hard work put into it. I just noticed one issue I am having with Importing the ".notes" file in Chrome, Firefox or Opera. When I try to import the .notes file in I get an error on import. I have deleted and emptied my browser cache also so there shouldn't be any conflicts of existing note files. One interesting thing I should note though is it works fine in IE11 or Edge just not any other browser.

**Comment by fabiobeoni** [comment]
Hi Mike, thanks for reporting the issue.

Can you please share your console log?
Thanks.

**Comment by mike-st** [comment]
Oh sure I tried from my local instance and your [example](https://fabiobeoni.github.io/adapt/) and ended up with the same error on either site. 

![notes_ext_not_working](https://user-images.githubusercontent.com/10455453/53045487-bd0e2580-345b-11e9-9bd1-54edf64f452e.jpg)

**Comment by mike-st** [comment]
Here is the file I am trying to import so you can test it out too. I zipped it up.

[Course_Notes.zip](https://github.com/fabiobeoni/adapt-notes/files/2881909/Course_Notes.zip)

**Comment by fabiobeoni** [comment]
Hi Mike, I suppose you cannot test the import feature running my sample the course under github... The console log says there are some restrictions enforced by github.

Put the course on you site or localhost and it should work.

**Comment by mike-st** [comment]
Thanks and good point. I got it up and running on my local 5000 instance and here is the console.log error I am getting...

![error-notes](https://user-images.githubusercontent.com/10455453/53669464-23a5f700-3c45-11e9-8614-256a10d7cc27.jpg)

**Comment by zarek3333** [comment]
Solution is to add: .replace('data:application/octet-stream;base64,','') on line 380 of adapt-notesView.js
